//! TuffBox core.
//!
//! This crate contains deterministic project, graph and resolver logic.
//! AI must not be used inside this crate.

pub mod change_plan;
pub mod crash;
pub mod diagnostics;
pub mod exporter;
pub mod forge_install;
pub mod graph;
pub mod graph_service;
pub mod http;
pub mod importer;
pub mod item_icons;
pub mod jre;
pub mod launcher;
pub mod download_cache;
pub mod lockfile;
pub mod manifest;
pub mod mc_install;
pub mod mod_files;
pub mod mod_index_cache;
pub mod mod_scan;
pub mod murmur2;
pub mod process;
pub mod provider;
pub mod resolver;
pub mod snapshot;
pub mod time_util;
pub mod updater;
pub mod versions;

pub mod adapters;
pub mod ai_explanation;
pub mod crash_assistant;
pub mod environment;
pub mod knowledge;
pub mod level_dat;
pub mod overrides;
pub mod properties_parser;
pub mod recipe_layout;
pub mod recipe_runtime;
pub mod recipe_scan;
pub mod registry;
pub mod tag_normalizer;
pub mod unified;

pub use change_plan::*;
pub use crash::*;
pub use diagnostics::*;
pub use exporter::*;
pub use forge_install::*;
pub use graph::*;
pub use graph_service::*;
pub use http::*;
pub use importer::*;
pub use item_icons::*;
pub use jre::*;
pub use launcher::*;
pub use lockfile::*;
pub use manifest::*;
pub use mc_install::*;
pub use mod_files::*;
pub use mod_index_cache::*;
pub use mod_scan::*;
pub use murmur2::*;
pub use process::*;
pub use provider::*;
pub use recipe_runtime::*;
pub use resolver::*;
pub use snapshot::*;
pub use updater::*;
pub use versions::*;
