<script lang="ts">
  import { CheckCircle2, PanelLeftClose, PanelRightClose, RefreshCw, Save, Search, Sparkles } from "@lucide/svelte";
  let { title = "Quest editor", chapterCount = 0, questCount = 0, dirty = false, saving = false, hasErrors = false, mode = "Quests", railCollapsed = false, inspectorCollapsed = false, onModeChange, onSave, onAi, onRefresh, onSearch, onToggleRail, onToggleInspector }: { title?: string; chapterCount?: number; questCount?: number; dirty?: boolean; saving?: boolean; hasErrors?: boolean; mode?: string; railCollapsed?: boolean; inspectorCollapsed?: boolean; onModeChange: (mode: string) => void; onSave: () => void; onAi: () => void; onRefresh: () => void; onSearch: () => void; onToggleRail: () => void; onToggleInspector: () => void } = $props();
  const modes = ["Quests", "Rewards", "Variables", "Logs"];
</script>

<header class="flex min-h-12 flex-wrap items-center justify-between gap-3 border-b border-white/[0.08] px-2 pb-3">
  <div class="flex min-w-0 items-center gap-2"><span class="text-base text-emerald-300">⚒</span><div class="min-w-0"><div class="truncate text-sm font-semibold text-neutral-100">{title}</div><div class="text-[11px] text-neutral-500">{chapterCount} chapters · {questCount} quests</div></div></div>
  <nav class="flex rounded-xl border border-white/10 bg-black/20 p-1" aria-label="Quest editor mode">{#each modes as item}<button type="button" class="rounded-lg px-3 py-1.5 text-xs transition {mode === item ? 'bg-emerald-500/15 text-emerald-200' : 'text-neutral-500 hover:text-neutral-200'}" onclick={() => onModeChange(item)}>{item}</button>{/each}</nav>
  <div class="flex items-center gap-2"><button type="button" class="hidden rounded-lg border border-white/10 p-2 text-neutral-400 hover:bg-white/10 lg:inline-flex" onclick={onToggleRail} title={railCollapsed ? 'Show chapters' : 'Hide chapters'}><PanelLeftClose size={15}/></button><button type="button" class="hidden rounded-lg border border-white/10 p-2 text-neutral-400 hover:bg-white/10 lg:inline-flex" onclick={onToggleInspector} title={inspectorCollapsed ? 'Show inspector' : 'Hide inspector'}><PanelRightClose size={15}/></button><span class="hidden items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] sm:inline-flex {hasErrors ? 'border-amber-500/30 bg-amber-500/10 text-amber-200' : 'border-emerald-500/30 bg-emerald-500/10 text-emerald-200'}"><CheckCircle2 size={12}/> {hasErrors ? 'Needs review' : dirty ? 'Unsaved' : 'Synced'}</span><button type="button" class="rounded-lg border border-white/10 p-2 text-neutral-400 hover:bg-white/10" onclick={onSearch} title="Search"><Search size={15}/><span class="sr-only">Search</span></button><button type="button" class="inline-flex items-center gap-1.5 rounded-lg border border-violet-400/25 bg-violet-500/10 px-3 py-2 text-xs text-violet-200 hover:bg-violet-500/20" onclick={onAi}><Sparkles size={14}/> Quest AI</button><button type="button" class="inline-flex items-center gap-1.5 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white shadow-[0_0_15px_rgba(16,185,129,0.18)] hover:bg-emerald-500" onclick={onSave} disabled={saving}><Save size={14}/> {saving ? 'Saving…' : 'Save'}<kbd class="hidden text-[10px] text-emerald-100/70 sm:inline">Ctrl S</kbd></button><button type="button" class="rounded-lg border border-white/10 p-2 text-neutral-400 hover:bg-white/10" onclick={onRefresh} disabled={saving}><RefreshCw size={15}/></button></div>
</header>
